# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-tcook-common"
BBFILE_PATTERN:meta-tcook-common = "^${LAYERDIR}/"

# Set a high priority to make this layer override lower layers other than speciality custom layers.
# This is to allow the common layer to override other layers that may be included in the build.
BBFILE_PRIORITY:meta-tcook-common = "90"

LAYERDEPENDS:meta-tcook-common = "core"
LAYERSERIES_COMPAT:meta-tcook-common = "scarthgap styhead blacksail wrynose"

BBFILES_DYNAMIC += "${LAYERDIR}/dynamic-layers/*/*.bb \
                    ${LAYERDIR}/dynamic-layers/*/*.bbappend"
