# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += " meta-tcook-common"
BBFILE_PATTERN_meta-tcook-common = "^${LAYERDIR}/"

# Set a high priority to make this layer override lower layers other than speciality custom layers.
# This is to allow the common layer to override other layers that may be included in the build.
BBFILE_PRIORITY_meta-tcook-common = "90"

LAYERDEPENDS_meta-tcook-common = "core"
LAYERSERIES_COMPAT_meta-tcook-common = "scarthgap styhead wrynose"

LAYERVERSION_meta-tcook-common = "1"

BBFILES_DYNAMIC += " \
    raspberrypi:${LAYERDIR}/dynamic-layers/*/*.bb \
    raspberrypi:${LAYERDIR}/dynamic-layers/*/*.bbappend"
