# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += " meta-tcook-common"
BBFILE_PATTERN_meta-tcook-common = "^${LAYERDIR}/"

# Set a high priority to make this layer override lower layers other than speciality custom layers.
# This is to allow the common layer to override other layers that may be included in the build.
BBFILE_PRIORITY_meta-tcook-common = "90"

LAYERDEPENDS_meta-tcook-common = " \
    core \
    openembedded-layer filesystems-layer gnome-layer meta-initramfs networking-layer perl-layer meta-python webserver xfce-layer \
    secure-core efi-secure-boot encrypted-storage ids integrity-layer signing-key tpm2 \
    security harden-layer integrity parsec-layer tpm-layer \
    virtualization-layer \
    meta-arm meta-arm-bsp meta-arm-systemready arm-toolchain \
    clang-layer \
"
LAYERSERIES_COMPAT_meta-tcook-common = "scarthgap styhead wrynose"

LAYERVERSION_meta-tcook-common = "1"

BBFILES_DYNAMIC += " \
    raspberrypi:${LAYERDIR}/dynamic-layers/recipes-*/*/*.bb \
    raspberrypi:${LAYERDIR}/dynamic-layers/recipes-*/*/*.bbappend"

IMAGE_FSTYPES += "wic wic.bmap"

EXTRA_IMAGE_FEATURES += " package-management rpm ssh-server-openssh"
PACKAGE_CLASSES = "package_rpm"

# Layers allowd to not have any direct bb files
ALLOW_EMPTY:lts-u-boot-mixin = "1"