DESCRIPTION = "Testing inclusion of Common Layer Dynamic Recipes"
LICENSE = "MIT"

ALLOW_EMPTY:${PN} = "1"

do_configure[nostamp] = "1"
do_configure() {
    bbwarn "
    
    PRR Common Layer included for:
    
    MACHINE: ${MACHINE} 
    SWVERSION: ${SWVERSION}

    Kernel Info:

    KERNEL_VERSION: ${KERNEL_VERSION}
    KERNEL_VERSION_STRING: ${KERNEL_VERSION_STRING}
    KERNEL_IMAGETYPE: ${KERNEL_IMAGETYPE}
    KERNEL_IMAGETYPES: ${KERNEL_IMAGETYPES}
    KERNEL_IMAGE_BASE_NAME: ${KERNEL_IMAGE_BASE_NAME}
    KERNEL_IMAGE_LINK_NAME: ${KERNEL_IMAGE_LINK_NAME}
    KERNEL_IMAGETYPE_SYMLINK: ${KERNEL_IMAGETYPE_SYMLINK}

    Image Setup:

    MACHINE_FEATURES: ${MACHINE_FEATURES}
    DISTRO_FEATURES: ${DISTRO_FEATURES}
    IMAGE_FEATURES: ${IMAGE_FEATURES}
    PACKAGE_CLASSES: ${PACKAGE_CLASSES}
    EXTRA_IMAGE_FEATURES: ${EXTRA_IMAGE_FEATURES}
    "
}